name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    uses: postboys/workflows/.github/workflows/build-nodejs.yml@main
    uses: postboys/workflows/.github/workflows/deploy.yml@main
