name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  test:
    run: echo 123
  build:
    uses: postboys/workflows/.github/workflows/build-nodejs.yml@main
