name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.SSH_HOST }}
    
  build:
    uses: postboys/workflows/.github/workflows/build-nodejs.yml@main
  
  deploy:
    needs: build
    uses: postboys/workflows/.github/workflows/deploy.yml@main
    secrets: inherit
