name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Just a placeholder
        run: echo "This enables the manual trigger button."
  
  build:
    uses: postboys/workflows/.github/workflows/build-nodejs.yml@main
