name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

permissions:
  contents: read

jobs:
  build:
    uses: postboys/workflows/.github/workflows/build-nodejs.yml@main
  
  deploy:
    needs: build
    uses: postboys/workflows/.github/workflows/deploy.yml@main
    secrets: inherit
